# Site Settings
theme                    : jekyll-theme-architect
locale                   : "en-UK"
title                    : "Phils Allergies"
description              : "What I can and cant eat... and some alternatives"
github:
  is_project_page        : false
